language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U setuptools
  - pip install coveralls
# command to run tests, e.g. python setup.py test
script: coverage run --source=lib/obfuscator --branch lib/setup.py test
after_success: coveralls
